<?xml version="1.0" encoding="utf-8"?><Database Name="ShiftScheduleDB" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=CPX-FKFC51GP1UV\SQLEXPRESS;Initial Catalog=ShiftScheduleDB;Integrated Security=True" SettingsObjectName="ShiftGenerator.Properties.Settings" SettingsPropertyName="ShiftScheduleDBConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Employees" Member="Employees">
    <Type Name="Employee">
      <Column Name="idEmployee" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="surname" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="jobContract" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="idTeam" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="independent" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="frenchlvl" Type="System.String" DbType="VarChar(5)" CanBeNull="true" />
      <Column Name="idUser" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Employee_EmpRequest" Member="EmpRequests" ThisKey="idEmployee" OtherKey="idEmployee" Type="EmpRequest" />
      <Association Name="Employee_EmpRequirement" Member="EmpRequirements" ThisKey="idEmployee" OtherKey="idEmployee" Type="EmpRequirement" />
      <Association Name="Employee_FTE" Member="FTEs" ThisKey="idEmployee" OtherKey="idEmployee" Type="FTE" />
      <Association Name="User_Employee" Member="User" ThisKey="idUser" OtherKey="idUser" Type="User" IsForeignKey="true" />
      <Association Name="Team_Employee" Member="Team" ThisKey="idTeam" OtherKey="idTeam" Type="Team" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.EmpRequests" Member="EmpRequests">
    <Type Name="EmpRequest">
      <Column Name="idEmpRequest" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="idEmployee" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="reqDesc" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="dateReq" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="dayNight" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="accepted" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="fulfilled" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="Employee_EmpRequest" Member="Employee" ThisKey="idEmployee" OtherKey="idEmployee" Type="Employee" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.EmpRequirements" Member="EmpRequirements">
    <Type Name="EmpRequirement">
      <Column Name="idEmpRequirements" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="idEmployee" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="reqDesc" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="dateReq" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="dayNight" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="fulfilled" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="Employee_EmpRequirement" Member="Employee" ThisKey="idEmployee" OtherKey="idEmployee" Type="Employee" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.FTE" Member="FTEs">
    <Type Name="FTE">
      <Column Name="idFTE" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="idEmployee" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="workingHours" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="workingHoursLast" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SPM" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Employee_FTE" Member="Employee" ThisKey="idEmployee" OtherKey="idEmployee" Type="Employee" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Users" Member="Users">
    <Type Name="User">
      <Column Name="idUser" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="password" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="permission" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="login" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="User_Employee" Member="Employees" ThisKey="idUser" OtherKey="idUser" Type="Employee" />
    </Type>
  </Table>
  <Table Name="dbo.Teams" Member="Teams">
    <Type Name="Team">
      <Column Name="idTeam" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="nameTeam" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="countEmp" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Team_Employee" Member="Employees" ThisKey="idTeam" OtherKey="idTeam" Type="Employee" />
    </Type>
  </Table>
  <Table Name="dbo.LawRequirements" Member="LawRequirements">
    <Type Name="LawRequirement">
      <Column Name="idRequirements" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="reqDesc" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
</Database>